# Generated by Django 4.2.1 on 2023-05-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterModelTable(
            name='token',
            table='user_tokens',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_users',
        ),
    ]
