# Generated by Django 4.2.1 on 2023-05-20 10:46

from django.db import migrations, models
import users.utils.model_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_firstname_alter_token_table_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=users.utils.model_helpers.expires_default),
        ),
        migrations.AddField(
            model_name='token',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
