# Generated by Django 4.2.1 on 2023-05-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('opened_date', models.DateField()),
                ('charter_capital', models.DecimalField(decimal_places=2, max_digits=8)),
                ('shop_size', models.CharField(choices=[('big', 'big'), ('medium', 'medium'), ('small', 'small')], max_length=255)),
            ],
        ),
    ]
