# Generated by Django 4.2.1 on 2023-05-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_context',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='task',
            table='task_tasks',
        ),
    ]
